### ISSUE TITLE
error C2167: '_setjmp': too many actual parameters for intrinsic function

### ISSUE THREAD

**Issue by narimiran** [status-im/nim-stew#133]
This error is happening on Windows CIs, both for Nim 1.2 and 1.6.

From what I can tell, it is just ignored (PRs with it are merged) for quite some time now.

----

I'm guessing it is connected to https://github.com/status-im/nimbus-eth2/issues/3121, which leads to https://github.com/nim-lang/Nim/pull/19924 (not yet merged) and https://github.com/nim-lang/Nim/pull/19959 (merged, but not backported).

----

EDIT: Already tracked here: https://github.com/nim-lang/Nim/issues/19957

**Comment by rockcavera** [comment]
What's the problem?
