### ISSUE TITLE
after change lib/system/arithmetics.nim proc inc to generic, the proc inc in this module cause  ambiguous call

### ISSUE THREAD

**Issue by bung87** [status-im/nim-stew#151]
see https://github.com/nim-lang/Nim/actions/runs/3463825054/jobs/5784591531

https://github.com/status-im/nim-stew/blob/1e86bd1ef38f78c601b07da7188e65785f2c0ed8/stew/interval_set.nim#L330

**Comment by Menduist** [comment]
What's the purpose of your linked PR?

**Comment by bung87** [comment]
the purpose is really make targeting compile target system int bit width, check `compiler/sigmatch.nim` changes.  before is match `tyInt` to `tyInt32`.

**Comment by arnetheduck** [comment]
While the `inc` function in `interval_set` looks like it could use a round of improvement indeed (ie it has overly broad matching and dubious utility vs `+=` cc @mjfh ), it's generally a good idea to avoid generic functions in core stdlib functions - if anything, you can overload instead which doesn't trigger nearly as many type resolution issues (and sometimes serve as "type anchors")

**Comment by bung87** [comment]
yeah, I agree, the orignal version already generic the poblem part is second argument `y = 1` which now matches to `tyInt`

**Comment by mjfh** [comment]
the `inc()` will be replaced by `incPt()` which should do the job
