### ISSUE TITLE
[Results] Stacktrace is eaten

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-stew#45]
It's currently harder to investigate with result as the stacktrace completely disappears in some cases:

https://github.com/status-im/nim-beacon-chain/pull/1163#issuecomment-644531631

![image](https://user-images.githubusercontent.com/22738317/85442488-83d65000-b590-11ea-8b6b-37defe6e4990.png)

**Comment by arnetheduck** [comment]
This is an issue with libbacktrace, not `result` - `result` just raises a `Defect` as normal..
