### ISSUE TITLE
Does byteutils need to import assign2 since arrayops imports and exports assign2?

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/nim-stew#99]
I frequently see:
```
.../stew/byteutils.nim(15, 3) Warning: imported and not used: 'assign2' [UnusedImport]
```
in compiler output. I know it's no big deal, but if the import isn't needed in byteutils then perhaps it can be removed to eliminate the warning?

**Comment by arnetheduck** [comment]
If tests compile without, it's not needed

**Comment by michaelsbradleyjr** [comment]
Tests pass, cf. #100.

**Comment by arnetheduck** [comment]
as a general tip, if you want to know if something is needed or not in the grander scheme of things, the best stress test we have is to clone `nimbus-eth2` and compile with your change enabled there - if `nimbus-eth2` compiles, so will everything else, most likely. cleanup patches like this are most welcome.
